[package]
name = "wire-structs"
version = "0.1.0"
edition = "2021"
authors = ["Kuba Karpierz <mr.karpierz@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[features]
serialization = []
deserialization = []