[workspace]
members = [
    "web",
    "generate_artifacts",
    "test_utils",
    "wire_structs",
    "web_wgpu",
    ]
resolver = "2"


[profile.dev]
opt-level = 3
debug = 1
[profile.test]
debug = 1
opt-level = 3
[profile.release]
opt-level = "s"
lto = true
