[package]
name = "wire-structs"
version = "0.1.0"
edition = "2021"
authors = ["Kuba Karpierz <mr.karpierz@gmail.com>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
glam = "0.21.1"
wire-structs = { path = "../wire_structs" }