[package]
name = "rendering"
version = "0.1.0"
authors = ["Kuba Karpierz <mr.karpierz@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
geometry = { path = "../geometry" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "renderer"
harness = false