[package]
name = "generate-artifacts"
version = "0.1.0"
edition = "2021"
authors = ["Kuba Karpierz <mr.karpierz@gmail.com>"]

[dependencies]
path-integration = { path = "../path_integration" }
serde = "1.0"
serde_json = { version = "1.0.82", features = ["float_roundtrip"] }